/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import form.model.ModelTabeleIgra;
import form.model.ModelTabeleRezultat;
import java.awt.Point;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JTable;
import model.Igra;
import model.RezultatIgre;

/**
 *
 * @author Jovana
 */
public class FormaPrikazIgri extends javax.swing.JFrame {

    /**
     * Creates new form FormaPrikazIgri
     */
    public FormaPrikazIgri() {
        initComponents();
        setLocationRelativeTo(null);
        popuniTabelu();
        ModelTabeleIgra mti = new ModelTabeleIgra(new ArrayList<>());
        jTableIGRE.setModel(mti);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableREZ = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableIGRE = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableREZ.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableREZ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableREZMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableREZ);

        jTableIGRE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableIGRE);

        jLabel1.setText("Prikaz rezultata igre");

        jLabel2.setText("Prikaz kombinacija koje je klijent poslao za odredjeni rezultat igre");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableREZMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableREZMouseClicked
        JTable tabela = (JTable) evt.getSource();
        Point p = evt.getPoint();
        int red = tabela.rowAtPoint(p);
        ModelTabeleRezultat mtr = (ModelTabeleRezultat) jTableREZ.getModel();
        List<RezultatIgre> lista = mtr.getList();
        RezultatIgre ri = lista.get(red);
        List<Igra> listaIgri = controller.Controller.getInstance().vratiIgreZaRezultat(ri);
        ModelTabeleIgra mti = new ModelTabeleIgra(listaIgri);
        jTableIGRE.setModel(mti);
    }//GEN-LAST:event_jTableREZMouseClicked

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableIGRE;
    private javax.swing.JTable jTableREZ;
    // End of variables declaration//GEN-END:variables

    private void popuniTabelu() {
        List<RezultatIgre> lista = controller.Controller.getInstance().vratiRezultate();
        ModelTabeleRezultat mtr = new ModelTabeleRezultat(lista);
        jTableREZ.setModel(mtr);
    }
}
