/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import forma.model.ModelTabeleIgra;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import model.Igra;
import niti.Nit;
import transfer.KlijentskiZahtev;
import transfer.ServerskiOdgovor;

/**
 *
 * @author Jovana
 */
public class KlijentskaForma extends javax.swing.JFrame {
    private niti.Nit n1;
    private niti.Nit n2;
    private niti.Nit n3;
    private niti.Nit n4;
    private int brPokusaja=0;
    
    /**
     * Creates new form KljijentskaForma
     */
    public KlijentskaForma() {
        initComponents();
        //popuni tabelu
        setLocationRelativeTo(null);
        ModelTabeleIgra mti = new ModelTabeleIgra(new ArrayList<>());
        jTableIGRA.setModel(mti);
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public void setjLabel4(JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButtonSTART1 = new javax.swing.JButton();
        jButtonSTOP1 = new javax.swing.JButton();
        jButtonSTART2 = new javax.swing.JButton();
        jButtonSTOP2 = new javax.swing.JButton();
        jButtonSTART3 = new javax.swing.JButton();
        jButtonSTOP3 = new javax.swing.JButton();
        jButtonSTART4 = new javax.swing.JButton();
        jButtonSTOP4 = new javax.swing.JButton();
        jButtonPOSALJI = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabelNA_MESTU = new javax.swing.JLabel();
        jLabelVAN_MESTA = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableIGRA = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel2.setText("0");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel3.setText("0");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel4.setText("0");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setText("0");

        jButtonSTART1.setText("start 1");
        jButtonSTART1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSTART1ActionPerformed(evt);
            }
        });

        jButtonSTOP1.setText("stop 1");
        jButtonSTOP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSTOP1ActionPerformed(evt);
            }
        });

        jButtonSTART2.setText("start 2");
        jButtonSTART2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSTART2ActionPerformed(evt);
            }
        });

        jButtonSTOP2.setText("stop 2");
        jButtonSTOP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSTOP2ActionPerformed(evt);
            }
        });

        jButtonSTART3.setText("start 3");
        jButtonSTART3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSTART3ActionPerformed(evt);
            }
        });

        jButtonSTOP3.setText("stop 3");
        jButtonSTOP3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSTOP3ActionPerformed(evt);
            }
        });

        jButtonSTART4.setText("start 4");
        jButtonSTART4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSTART4ActionPerformed(evt);
            }
        });

        jButtonSTOP4.setText("stop 4");
        jButtonSTOP4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSTOP4ActionPerformed(evt);
            }
        });

        jButtonPOSALJI.setText("POSALJI");
        jButtonPOSALJI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPOSALJIActionPerformed(evt);
            }
        });

        jLabel5.setText("Broj pogodjenih na mestu: ");

        jLabel6.setText("Broj pogodjenih van mesta: ");

        jLabelNA_MESTU.setText("0");

        jLabelVAN_MESTA.setText("0");

        jTableIGRA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableIGRA);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(37, 37, 37)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelNA_MESTU, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabelVAN_MESTA, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 238, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonSTOP1)
                                    .addComponent(jButtonSTART1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonSTOP2)
                                    .addComponent(jButtonSTART2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonSTOP3)
                                    .addComponent(jButtonSTART3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButtonSTOP4)
                                            .addComponent(jButtonSTART4))
                                        .addGap(21, 125, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButtonPOSALJI))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButtonSTART2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel2)
                            .addGap(18, 18, 18)
                            .addComponent(jButtonSTOP2))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jButtonSTART1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addComponent(jButtonSTOP1)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonSTART4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jButtonPOSALJI)))
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSTOP4))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonSTART3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSTOP3)))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNA_MESTU))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabelVAN_MESTA))
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSTART1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSTART1ActionPerformed
        n1=new Nit(jLabel1);
        n1.start();
    }//GEN-LAST:event_jButtonSTART1ActionPerformed

    private void jButtonSTART2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSTART2ActionPerformed
       n2=new Nit(jLabel2);
        n2.start();
    }//GEN-LAST:event_jButtonSTART2ActionPerformed

    private void jButtonSTART3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSTART3ActionPerformed
        n3=new Nit(jLabel3);
        n3.start();
    }//GEN-LAST:event_jButtonSTART3ActionPerformed

    private void jButtonSTART4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSTART4ActionPerformed
        n4=new Nit(jLabel4);
        n4.start();
    }//GEN-LAST:event_jButtonSTART4ActionPerformed

    private void jButtonSTOP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSTOP1ActionPerformed
        n1.zaustaviNit();
    }//GEN-LAST:event_jButtonSTOP1ActionPerformed

    private void jButtonSTOP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSTOP2ActionPerformed
        n2.zaustaviNit();
    }//GEN-LAST:event_jButtonSTOP2ActionPerformed

    private void jButtonSTOP3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSTOP3ActionPerformed
        n3.zaustaviNit();
    }//GEN-LAST:event_jButtonSTOP3ActionPerformed

    private void jButtonSTOP4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSTOP4ActionPerformed
        n4.zaustaviNit();
    }//GEN-LAST:event_jButtonSTOP4ActionPerformed

    private void jButtonPOSALJIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPOSALJIActionPerformed
        String kombinacija = jLabel1.getText()+"-"+jLabel2.getText()+"-"+jLabel3.getText()+"-"+jLabel4.getText();
        Igra i = new Igra(-1, kombinacija, -1, -1);
        KlijentskiZahtev kz = new KlijentskiZahtev(i, operacije.Operacije.POGODI_KOMBINACIJU);
        komunikacija.Komuniakcija.getInstance().posaljiZahtev(kz);
        //
        ServerskiOdgovor so = komunikacija.Komuniakcija.getInstance().primiOdgovor();
        i=(Igra) so.getOdgovor();
        if(i!=null){
            jLabelNA_MESTU.setText(i.getBrNaMestu()+"");
            jLabelVAN_MESTA.setText(i.getBrVanMesta()+"");
            //dodaj u tabelu kombianciju 
            ModelTabeleIgra mti = (ModelTabeleIgra) jTableIGRA.getModel();
            mti.dodajIgru(i);
            if(i.getBrNaMestu()==4){
                JOptionPane.showMessageDialog(null, "Pobedili ste!", "Uspeh", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            }else{
                brPokusaja++;
                if(brPokusaja==6){
                   JOptionPane.showMessageDialog(null, "Izgubili ste!", "Nesupesna igra", JOptionPane.ERROR_MESSAGE);
                   this.dispose();
                }
            }
        }else{
            System.out.println("greska igra je null");
        }
    }//GEN-LAST:event_jButtonPOSALJIActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KlijentskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KlijentskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KlijentskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KlijentskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KlijentskaForma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPOSALJI;
    private javax.swing.JButton jButtonSTART1;
    private javax.swing.JButton jButtonSTART2;
    private javax.swing.JButton jButtonSTART3;
    private javax.swing.JButton jButtonSTART4;
    private javax.swing.JButton jButtonSTOP1;
    private javax.swing.JButton jButtonSTOP2;
    private javax.swing.JButton jButtonSTOP3;
    private javax.swing.JButton jButtonSTOP4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelNA_MESTU;
    private javax.swing.JLabel jLabelVAN_MESTA;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableIGRA;
    // End of variables declaration//GEN-END:variables

   
}
